name: enquetes
description: Projeto de enquetes.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  http: ^0.13.4
  rxdart: ^0.27.3
  flutter_riverpod: ^1.0.4
  hooks_riverpod: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  test: ^1.21.1
  mocktail: ^0.3.0
  faker: ^2.0.0
  flutter_launcher_icons: 0.9.2

flutter:
  uses-material-design: true
  assets:
    - lib/ui/assets/

flutter_icons:
  ios: true
  android: true
  image_path_android: lib/ui/assets/icon/android.png
  image_path_ios: lib/ui/assets/icon/ios.png
  adaptive_icon_background: lib/ui/assets/icon/background.png
  adaptive_icon_foreground: lib/ui/assets/icon/foreground.png